### PR TITLE
Removed the attributes from the signatures

### PR DESCRIPTION
**Pull request by MecuSorin**
Removes attributes from signature (part of #8)

### CODE REVIEW

**Comment by baronfel** [comment]
An open question I have here is if we want to remove all attributes all the time. I can see commonly-disregarded attributes like DebuggerDisplay/CompiledName being stripped out, but I think it can often be useful to see attributes applied to types (especially records, classes, and unions). Modules/functions maybe not so much.

**Comment by dsyme** [comment]
> An open question I have here is if we want to remove all attributes all the time. I can see commonly-disregarded attributes like DebuggerDisplay/CompiledName being stripped out, but I think it can often be useful to see attributes applied to types (especially records, classes, and unions). Modules/functions maybe not so much.

Yes, we need to be more nuanced here.  But this is a good start

**Comment by Krzysztof-Cieslak** [comment]
This is bad changed - we removed all cases of potentially useful information because some cases maybe not useful. I don't see how it's good design.

**Comment by dsyme** [comment]
> This is bad changed - we removed all cases of potentially useful information because some cases maybe not useful. I don't see how it's good design.

We will add them back in as they are specifically identified as useful.

I know some attributes must be included.  But we must simplify the presentation of the docs to reduce the information overload.

**Comment by dsyme** [comment]
> I know some attributes must be included. But we must simplify the presentation of the docs to reduce the information overload.

My plan is to go over the generated docs for FSharp.Core, FSharp.Formatting, FSharp.Data, and DiffSharp to make sure everything is really very beautiful, simple and clear.

If you have a "north star" for most beautiful technical docs that we can emulate please let me know

**Comment by dsyme** [comment]
My current belief is that any generated docs coming out of anything based on FSHarp.Formatting ApiDocsModel are nowhere near where we need them to be.  We have a huge amount to do and there will be a lot of back and forth.  

After the long discussion in the Dugnad session the other evening, these docs are now on a path to effectively be replacing (or acting as a surrogate for) the Microsoft FSharp.Core docs. So we need to be as simple and well documented as those.

**Comment by dsyme** [comment]
https://github.com/fsharp/fsharp-core-api-docs/issues/21

**Pull request merged**
